### ISSUE TITLE
False Positive: Itch.io

### ISSUE THREAD

**Issue by Antsy4904** [VernonStow/Filterlist#16]
https://itch.io/ is a legit place to download and purchase digital content, most of of the images seem to be hosted on `https://img.itch.zone/`.

Speaking of this, does this list have to be all requests? can't it be only or mostly `^document` if you catch my drift? Lots of websites are bound to host CDNs on silly domains like this and the shady ones are probably not doing that... they are mostly using it on the main website domain only.

Just a thought, would bring down potential false positives a lot.

**Comment by VernonStow** [comment]
Fixed in https://github.com/VernonStow/Filterlist/commit/dadac8c6fec177fc2cf4f005764de5883890f033

The reason to block $all is to prevent scripts or i-frames from the blocked domains, but I'll look into it further.

**Comment by Antsy4904** [comment]
I realize now that I forgot to check that it got fixed cause it seems you did it correctly but.. the images are still getting blocked somehow?

Maybe it's not a match because its on `img.itch.zone` and not `itch.zone`? If that's it then would have made the same mistake honestly..

<details><summary>Logger output</summary>

| | | | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +4 |  |  | itch.io | 1 | get | image | `https://itch.io/ca.gif?x=t1s1o1EtlxbEy6x4F17bc1F17dozF17kq0F17v1aF19lv2F19qp9F1b6k9F1bjgfF1c08zF1c84uF1cbq4Ejtrxs6F1bx51&s=3%3A1` |
| +2 | \|\|zone^$from=~blahaj.zone\|~froth.zone\|~itch.zone | -- | itch.io | 3 | get | image | `https://img.itch.zone/aW1nLzgwNDY3NDgucG5n/300x240%23c/9%2FY7o2.png` |
| +2 | \|\|zone^$from=~blahaj.zone\|~froth.zone\|~itch.zone | -- | itch.io | 3 | get | image | `https://img.itch.zone/aW1nLzEzMTM3MzAzLnBuZw==/300x240%23c/o8mTX2.png` |
| +2 | \|\|zone^$from=~blahaj.zone\|~froth.zone\|~itch.zone | -- | itch.io | 3 | get | image | `https://img.itch.zone/aW1nLzEzMTIyNzk2LnBuZw==/300x240%23c/x8BqyS.png` |
| +2 | \|\|zone^$from=~blahaj.zone\|~froth.zone\|~itch.zone | -- | itch.io | 3 | get | image | `https://img.itch.zone/aW1nLzEzMTQyNjkwLmdpZg==/300x240%23cm/9gymzO.gif` |
| +2 | \|\|zone^$from=~blahaj.zone\|~froth.zone\|~itch.zone | -- | itch.io | 3 | get | image | `https://img.itch.zone/aW1nLzExNjMyNTcwLnBuZw==/300x240%23c/YJ5lAA.png` |
| +2 | \|\|zone^$from=~blahaj.zone\|~froth.zone\|~itch.zone | -- | itch.io | 3 | get | image | `https://img.itch.zone/aW1nLzEzMjA5NzQ3LmdpZg==/300x240%23cm/O7Xpy4.gif` |
| +2 | \|\|zone^$from=~blahaj.zone\|~froth.zone\|~itch.zone | -- | itch.io | 3 | get | image | `https://img.itch.zone/aW1nLzExODg1OTUxLmpwZw==/300x240%23c/85%2BYKQ.jpg` |
| +2 | \|\|zone^$from=~blahaj.zone\|~froth.zone\|~itch.zone | -- | itch.io | 3 | get | image | `https://img.itch.zone/aW1nLzEzMzM1MDI5LnBuZw==/300x240%23c/GX1e%2FB.png` |
| +2 | \|\|zone^$from=~blahaj.zone\|~froth.zone\|~itch.zone | -- | itch.io | 3 | get | image | `https://img.itch.zone/aW1nLzEyMDgzMDA0LmdpZg==/300x240%23cm/3Oz%2F7N.gif` |
| +2 | \|\|zone^$from=~blahaj.zone\|~froth.zone\|~itch.zone | -- | itch.io | 3 | get | image | `https://img.itch.zone/aW1nLzEyNTc4NjA3LnBuZw==/300x240%23c/PCrMiq.png` |
| +2 | \|\|zone^$from=~blahaj.zone\|~froth.zone\|~itch.zone | -- | itch.io | 3 | get | image | `https://img.itch.zone/aW1nLzEzMjY3MDgwLnBuZw==/300x240%23c/G%2FZcOd.png` |
| +2 | \|\|zone^$from=~blahaj.zone\|~froth.zone\|~itch.zone | -- | itch.io | 3 | get | image | `https://img.itch.zone/aW1nLzUyMzA5MzkucG5n/300x240%23c/9JaJN8.png` |
| +2 | \|\|zone^$from=~blahaj.zone\|~froth.zone\|~itch.zone | -- | itch.io | 3 | get | image | `https://img.itch.zone/aW1nLzEzMzY1MDMzLmdpZg==/300x240%23cm/WZJuX6.gif` |
| +2 | \|\|zone^$from=~blahaj.zone\|~froth.zone\|~itch.zone | -- | itch.io | 3 | get | image | `https://img.itch.zone/aW1nLzEzMzgzNTM5LnBuZw==/300x240%23c/Tvidtj.png` |
| +2 | ##.sidebar_social |  | itch.io |  | get | dom | `https://itch.io/` |
| +2 | ##.icon-twitter |  | itch.io |  | get | dom | `https://itch.io/` |
| +2 | ##.icon-reddit |  | itch.io |  | get | dom | `https://itch.io/` |
| +2 | ##.icon-facebook |  | itch.io |  | get | dom | `https://itch.io/` |
| +2 | ##.header_widget, .index_sidebar:style(position: absolute !important;) |  | itch.io |  | get | dom | `https://itch.io/` |
| +2 |  |  | itch.io | 1 | get | image | `https://itch.io/favicon.ico` |
| +1 |  |  | itch.io | 1 | get | font | `https://static.itch.io/icons/fonts/icomoon.ttf?4ibnvg` |
| +1 |  |  | itch.io | 1 | get | font | `https://static.itch.io/fonts/lato-v14-latin-900.woff2` |
| +1 |  |  | itch.io | 1 | get | image | `https://static.itch.io/images/youtube_icon.svg` |
| +1 |  |  | itch.io | 3 | get | image | `https://i.ytimg.com/vi/jUpv8QT4cmk/hqdefault.jpg` |
| +1 | \|\|zone^$from=~blahaj.zone\|~froth.zone\|~itch.zone | -- | itch.io | 3 | get | image | `https://img.itch.zone/aW1hZ2UvMjIzNTc4MS8xMzIzODU1Ny5wbmc=/794x1000d/FO0D0x.png` |
| +1 |  |  | itch.io | 1 | get | image | `https://static.itch.io/images/app-banner.png` |
| +1 |  |  | itch.io | 1 | get | image | `https://static.itch.io/images/logo-black-new.svg` |
| +1 | \|\|zone^$from=~blahaj.zone\|~froth.zone\|~itch.zone | -- | itch.io | 3 | get | image | `https://img.itch.zone/aW1hZ2UvMjIzNTc4MS8xMzIzODU1OS5wbmc=/220x123%23cm/kWKZRc.png` |
| +1 | \|\|zone^$from=~blahaj.zone\|~froth.zone\|~itch.zone | -- | itch.io | 3 | get | image | `https://img.itch.zone/aW1hZ2UvMjIzNTc4MS8xMzIzODU1OC5wbmc=/220x123%23cm/9ycshC.png` |
| +1 | \|\|zone^$from=~blahaj.zone\|~froth.zone\|~itch.zone | -- | itch.io | 3 | get | image | `https://img.itch.zone/aW1hZ2UvMjIzNTc4MS8xMzIzODU1Ny5wbmc=/220x123%23cm/t70wD7.png` |
| +1 | googletagmanager_gtm.js | << | itch.io | 3 | get | script | `https://www.googletagmanager.com/gtag/js?id=G-36R7NPBMLS` |
| +1 | \|\|googletagmanager.com/gtag/js$script,redirect-rule=googletagmanager_gtm.js:5 | -- | itch.io | 3 | get | script | `https://www.googletagmanager.com/gtag/js?id=G-36R7NPBMLS` |
| +1 | * googletagmanager.com * block | -- | itch.io | 3 | get | script | `https://www.googletagmanager.com/gtag/js?id=G-36R7NPBMLS` |
| +1 | \|\|zone^$from=~blahaj.zone\|~froth.zone\|~itch.zone | -- | itch.io | 3 | get | image | `https://img.itch.zone/aW1hZ2UvMjIzNTc4MS8xMzIzODU1OS5wbmc=/220x123%23cm/kWKZRc.png` |
| +1 | \|\|zone^$from=~blahaj.zone\|~froth.zone\|~itch.zone | -- | itch.io | 3 | get | image | `https://img.itch.zone/aW1hZ2UvMjIzNTc4MS8xMzIzODU1OC5wbmc=/220x123%23cm/9ycshC.png` |
| +1 | \|\|zone^$from=~blahaj.zone\|~froth.zone\|~itch.zone | -- | itch.io | 3 | get | image | `https://img.itch.zone/aW1hZ2UvMjIzNTc4MS8xMzIzODU1Ny5wbmc=/220x123%23cm/t70wD7.png` |
| +1 |  |  | itch.io | 1 | get | script | `https://static.itch.io/index.min.js?1694634831` |
| +1 |  |  | itch.io | 1 | get | script | `https://static.itch.io/react.min.js?1694634831` |
| +1 |  |  | itch.io | 1 | get | script | `https://static.itch.io/lib.min.js?1694634831` |
| +1 |  |  | itch.io | 1 | get | css | `https://static.itch.io/main.css?1694634831` |
| +1 |  |  | raru.re | 0,3 | get | xhr | `https://r3-m.b-cdn.net/` | `aliasURL=https://cdn.raru.re/cache/media_attachments/files/111/074/750/678/835/009/original/fabcb85be5ee93b0.png` |
| +1 |  |  | raru.re | 0,1 | get | xhr | `https://cdn.raru.re/cache/media_attachments/files/111/074/750/678/835/009/original/fabcb85be5ee93b0.png` |
| +1 |  |  | raru.re | 0,3 | get | xhr | `https://r3-m.b-cdn.net/` | `aliasURL=https://cdn.raru.re/cache/media_attachments/files/111/074/750/678/835/009/small/fabcb85be5ee93b0.png` |
| +1 |  |  | raru.re | 0,1 | get | xhr | `https://cdn.raru.re/cache/media_attachments/files/111/074/750/678/835/009/small/fabcb85be5ee93b0.png` |
| +1 |  |  | raru.re | 0,3 | get | xhr | `https://r3-m.b-cdn.net/` | `aliasURL=https://cdn.raru.re/cache/accounts/avatars/109/362/415/239/140/758/original/f70ff67355f97463.png` |
| +1 |  |  | raru.re | 0,1 | get | xhr | `https://cdn.raru.re/cache/accounts/avatars/109/362/415/239/140/758/original/f70ff67355f97463.png` |
| +0 |  |  | itch.io | 1 | get | doc | `https://itch.io/` |
</details>

**Comment by iam-py-test** [comment]
$domain applies to the domain making the request, not the domain being requested. Since itch.io and not itch.zone is making the request, it is still blocked (sorry if that's confusing): https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#domain
I think denyallow work better: https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#denyallow
```adblock
||zone^$all,denyallow=itch.zone,domain=~blahaj.zone|~froth.zone
```
Thanks

**Comment by VernonStow** [comment]
Thanks, @Antsy4904 and @iam-py-test . Images hosted on img.itch.zone are loading OK for me after the suggested rewrite and force updating the filter.

I haven't been able to find any noteworthy documentation on why some other lists only block $doc for suspicious TLDs, but I'd be interested if someone can provide more info.
